config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root "events#index"

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get :join
      get :recruit
    end
  end

  resources :events do
    resources :participations, only: [:create, :destroy]
    get 'search', on: :collection
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  
  has_many :events, class_name: 'Event', foreign_key: :owner_id, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :join_events, through: :participations, source: :event
  has_many :sns_credentials
  validates :name, presence: true, uniqueness: true
  mount_uploader :image, ImageUploader, dependent: :destroy

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def join
    @events_join = User.find_by(params[:id]).join_events
  end

  def recruit
    @events_recruit = User.find_by(params[:id]).events
  end

end

app/views/users/_mypage_left_nav.html.haml
#MypageLeftNav
  %ul.MypageSubmenu
    %li.Heading
      %h6.font-weight-bold.line-height-28px マイページ
    .SubHeading.NavBorderTop
      %li
        %h6 イベント管理
      %li.item.current
        = link_to "参加状況", join_user_path(current_user)
      %li.item
        = link_to "募集状況", "#"
      -# %li.item
      -#   = link_to "下書き", "#"
      -# %li.item
      -#   = link_to "登録開催エリア", "#"
    .SubHeading.NavBorderTop
      %li
        %h6 会員登録情報
      %li.item
        - if user_signed_in? && current_user.id == params[:id].to_i
          = link_to "お客様情報", edit_user_registration_path(params[:id].to_i)
        - else
          = link_to "お客様情報", user_path(params[:id].to_i)
      -# %li.item
      -#   = link_to "クレジットカード", "#"
      -# %li.item
      -#   = link_to "振込口座", "#"
    .SubHeading.NavBorderTop
      %li
        %h6 お気に入りユーザー
      -# %li.item
      -#   = link_to "フォロー", "#"
      -# %li.item
      -#   = link_to "フォロワー", "#"

app/views/users/_mypage_right_content.html.haml
#MypageRightContent
  %h4 ○○様のマイページ
  %ul.eventTab
    %li#eventJoin.current
      = link_to "参加", "#"
    %li#eventRecruit
      = link_to "募集", "#"
  .EventIndex
    - if @events_join.empty?
      参加イベント履歴はありません。
    - else
      .EventTitle
        イベント一覧
      .EventLists
        - @events_join.each do |event|
          .Event.card.shadow
            .avatar.mx-auto.white
              - if event.owner.image?
                = image_tag event.owner.image.to_s, class: "rounded-circle img-responsive"
              - else
                = image_tag 'no_image.jpg', class: "rounded-circle img-responsive"
            .card-body
              %h4.Event__user.card-title.font-weight-bold
                = event.owner.name
              %hr
              .Event__content
                .Event__title
                  = event.name
                .Event__datetime
                  = "#{event.start_time.strftime("%Y年%m月%d日 %H時%M分")} 〜 #{event.start_time.strftime("%Y年%m月%d日 %H時%M分")}"
                .Event__place
                  = event.place
              %hr
              .Event__btn
                = render partial: '/events/participation_form', locals: { event: event }

app/views/users/join.html.haml
.MypageContent
  = render partial: 'users/mypage_left_nav'
  #MypageRightContent
    %h4 ○○様のマイページ
    %ul.eventTab
      %li#eventJoin.current
        = link_to "参加", "#"
      %li#eventRecruit
        = link_to "募集", "#"
    .EventIndex
      - if @events_join.empty?
        参加イベント履歴はありません。
      - else
        .EventTitle
          イベント一覧
        .EventLists
          - @events_join.each do |event|
            .Event.card.shadow
              .avatar.mx-auto.white
                - if event.owner.image?
                  = image_tag event.owner.image.to_s, class: "rounded-circle img-responsive"
                - else
                  = image_tag 'no_image.jpg', class: "rounded-circle img-responsive"
              .card-body
                %h4.Event__user.card-title.font-weight-bold
                  = event.owner.name
                %hr
                .Event__content
                  .Event__title
                    = event.name
                  .Event__datetime
                    = "#{event.start_time.strftime("%Y年%m月%d日 %H時%M分")} 〜 #{event.start_time.strftime("%Y年%m月%d日 %H時%M分")}"
                  .Event__place
                    = event.place
                %hr
                .Event__btn
                  = render partial: '/events/participation_form', locals: { event: event }

app/views/users/recruit.html.haml
.MypageContent
  = render partial: 'users/mypage_left_nav'
  #MypageRightContent
    %h4 ○○様のマイページ
    %ul.eventTab
      %li#eventJoin.current
        = link_to "参加", "#"
      %li#eventRecruit
        = link_to "募集", "#"
    .EventIndex
      - if @events_recruit.empty?
        参加イベント履歴はありません。
      - else
        .EventTitle
          イベント一覧
        .EventLists
          - @events_recruit.each do |event|
            .Event.card.shadow
              .avatar.mx-auto.white
                - if event.owner.image?
                  = image_tag event.owner.image.to_s, class: "rounded-circle img-responsive"
                - else
                  = image_tag 'no_image.jpg', class: "rounded-circle img-responsive"
              .card-body
                %h4.Event__user.card-title.font-weight-bold
                  = event.owner.name
                %hr
                .Event__content
                  .Event__title
                    = event.name
                  .Event__datetime
                    = "#{event.start_time.strftime("%Y年%m月%d日 %H時%M分")} 〜 #{event.start_time.strftime("%Y年%m月%d日 %H時%M分")}"
                  .Event__place
                    = event.place
                  .Event__level
                    = event.level
                  .Event__tag
                    - event.tags.each do |tag|
                      = tag
                %hr
                .Event__btn
                  = render partial: '/events/participation_form', locals: { event: event }

app/views/users/show.html.haml
%h1 ユーザー情報