config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root "events#index"

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get :join
      get :recruit
    end
  end

  resources :events do
    resources :participations, only: [:create, :destroy]
    get 'search', on: :collection
  end
end

app/models/event.rb
class Event < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :participations
  has_many :join_users, through: :participations, source: :user
  belongs_to :owner, class_name: 'User'
  belongs_to_active_hash :level

  include ActiveModel::Validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :place, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 250 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates_with EventValidator

  acts_as_taggable #追加
  # acts_as_taggable_on :tags　と同じ意味のエイリアス
  # tags のなかにIDやら名前などが入る。イメージ的には親情報。

  # current_userがすでに参加しているかどうかのメソッド
  def participated_by?(user)
      participations.where(user_id: user.id).exists?
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if user_signed_in?
      @events = Event.includes(:owner).where.not('owner_id = ?', current_user).where('start_time > ?', Time.zone.now).order(:start_time)
    else
      @events = Event.includes(:owner).where('start_time > ?', Time.zone.now).order(:start_time)
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.events.build
  end 

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to root_path, notice: 'イベントを作成しました'
    else
      render :new
    end
  end

  def edit
    @event = current_user.events.find(params[:id])
  end

  def update
    @event = current_user.events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'イベントを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy
    redirect_to root_path, notice: '削除しました'
  end

  def search
    @events = Event.search(params[:keyword]).where.not('owner_id = ?', current_user)
  end

  private

    def event_params
      params.require(:event).permit(:name, :place, :content, :start_time, :end_time, :level_id, :tag_list)
    end

end

app/views/events/_cancel.html.haml
= form_with model: participation = event.participations.find_by(user_id: current_user.id), url: "/events/#{event.id}/participations/#{participation.id}", method: :delete, remote: true do |f|
  = f.submit "参加キャンセルする", class: "btn btn-secondary", data: { confirm: '本当にキャンセルしますか？' }

app/views/events/_event.html.haml
.Event.card.shadow
  .avatar.mx-auto.white
    - if event.owner.image?
      = image_tag event.owner.image.to_s, class: "rounded-circle img-responsive"
    - else
      = image_tag 'no_image.jpg', class: "rounded-circle img-responsive"
  .card-body
    %h4.Event__user.card-title.font-weight-bold
      = event.owner.name
    %hr
    .Event__content
      .Event__title
        = event.name
      .Event__datetime
        = "#{event.start_time.strftime("%Y年%m月%d日 %H時%M分")} 〜 #{event.start_time.strftime("%Y年%m月%d日 %H時%M分")}"
      .Event__place
        = event.place
      .Event__level
        - if event.level_id.present?
          = event.level.name
        - else
          レベル指定なし
      .Event__tag
        - event.tags.each do |tag|
          = tag
    %hr
    .Event__btn
      = render partial: 'events/participation_form', locals: { event: event }

app/views/events/_event_form.html.haml
.Event.card.shadow
  .avatar.mx-auto.white
    - if event.owner.image?
      = image_tag event.owner.image.to_s, class: "rounded-circle img-responsive"
    - else
      = image_tag 'no_image.jpg', class: "rounded-circle img-responsive"
  .card-body
    %h4.Event__user.card-title.font-weight-bold
      = event.owner.name
    %hr
    .Event__content
      .Event__title
        = event.name
      .Event__datetime
        = "#{event.start_time.strftime("%Y年%m月%d日 %H時%M分")} 〜 #{event.start_time.strftime("%Y年%m月%d日 %H時%M分")}"
      .Event__place
        = event.place
    %hr
    .Event__btn
      - if user_signed_in?
        = render partial: 'participation_form', locals: { event: event }

app/views/events/_form.html.haml
.SettingEventForm
  = form_with model: @event, local: true do |f|
    %h3.SettingEventForm__group イベント作成
    = render 'shared/error_messages', locals: { event: @event }
    .SettingEventForm__group
      .SettingEventForm__label
        = f.label :name, "イベント名"
      .SettingEventForm__field
        = f.text_field :name, class: "form-control"
    .SettingEventForm__group
      .SettingEventForm__label
        = f.label :place, "開催場所"
      .SettingEventForm__field
        = f.text_field :place, class: "form-control"
    .SettingEventForm__group
      .SettingEventForm__label
        = f.label :start_time
      .SettingEventForm__field
        = f.datetime_select :start_time, use_month_numbers: true, start_year: Time.zone.now.year, end_year: Time.zone.now.year + 1, minute_step: 10, class: "form-control"
    .SettingEventForm__group
      .SettingEventForm__label
        = f.label :end_time
      .SettingEventForm__field
        = f.datetime_select :end_time, use_month_numbers: true, start_year: Time.zone.now.year, end_year: Time.zone.now.year + 1, minute_step: 10, class: "form-control"
    .SettingEventForm__group
      .SettingEventForm__label
        = f.label :tag_list, "タグ"
      .SettingEventForm__field
        = f.text_field :tag_list, value: @event.tag_list.join(','), class: "form-control"
    .SettingEventForm__group
      .SettingEventForm__label
        = f.label :content, "イベントの詳細"
      .SettingEventForm__field
        = f.text_area :content, row: 10, class: "form-control"
    %button#levelBtn.btn.btn-primary 推奨レベルを追加
    #levelRange
      .SettingEventForm__group.SettingEventForm__btn.displayNone
        .SettingEventForm__label
          = f.label :level_id, "参加者の推奨レベル："
          %span#score 中級
        .SettingEventForm__field
          = f.range_field :level_id, min: 1, max: 5, class: "form-control-range", id: "slider", style: "width: 500px;", disabled: true
    .SettingEventForm__group.SettingEventForm__btn
      = f.submit class: "btn btn-primary text-white"

app/views/events/_participate.html.haml
= form_with model: event.participations.build, url: event_participations_path(event),remote: true do |f|
  = hidden_field_tag :event_id, event.id
  = f.submit "イベントに参加する", class: "btn btn-primary text-white", data: { confirm: '参加確定してもよろしいですか？' }

app/views/events/_participation_form.html.haml
- if !user_signed_in?
  = link_to "イベントに参加する", new_user_session_path, class: "btn btn-primary text-white"
- else
  #follow_form
  - unless event.participated_by?(current_user)
    = render partial: 'events/participate', locals: { event: event }
  - else
    = render partial: 'events/cancel', locals: { event: event }

app/views/events/edit.html.haml
= render 'events/form'

app/views/events/index.html.haml
.Main
  .EventSearch.border
    = form_with(url: search_events_path, local: true, method: :get, class: "input-group") do |f|
      .input-group-prepend
        %span.input-group-text
          %label
            = icon('fas', 'search')
            = f.submit "検索", class: "sr-only"
      = f.text_field :keyword, placeholder: "イベントを検索する", class: "form-control rounded-right"
  .EventIndex
    .EventTitle
      イベント一覧
    .EventLists
      - if @events.empty?
        投稿されたイベントはありません。
      - else
        = render @events

app/views/events/new.html.haml
= render 'events/form'

app/views/events/search.html.haml
.Main
  .EventSearch.border
    = form_with(url: search_events_path, local: true, method: :get, class: "input-group") do |f|
      .input-group-prepend
        %span.input-group-text
          %label
            = icon('fas', 'search')
            = f.submit "検索", class: "sr-only"
      = f.text_field :keyword, placeholder: "イベントを検索する", class: "form-control rounded-right"
  .EventIndex
    .EventTitle
      イベント一覧
    .EventLists
      = render @events

app/views/events/show.html.haml
%h1
  = @event.name
%div
  主催者：
  = @event.owner.name
%div
  開催時間：
  = "#{@event.start_time.strftime("%Y年%m月%d日 %H時%M分")} 〜 #{@event.start_time.strftime("%Y年%m月%d日 %H時%M分")}" 
%div
  開催場所：
  = @event.place
%div
  イベント詳細：
  = @event.content
- if user_signed_in? && current_user.id == @event.owner_id
  %div
    = link_to 'イベントを編集する', edit_event_path(@event), class: "btn btn-outline-dark"
    = link_to 'イベントを削除する', event_path(@event),data: { confirm: "本当に削除しますか？" }, method: :delete, class: "btn btn-outline-dark"