config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root "events#index"

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get :join
      get :recruit
    end
  end

  resources :events do
    resources :participations, only: [:create, :destroy]
    get 'search', on: :collection
  end
end

app/views/layouts/_header.html.haml
%header.Header
  .Logo
    =link_to root_path do
      イベサク
  .Icons
    - if user_signed_in?
      .Icons__icon
        = link_to join_user_path(current_user) do
          .Icons__icon--user
            = icon('fas', 'user')
          .Icons__text
            マイページ
      .Icons__icon
        = link_to new_event_path do
          .Icons__icon--plus
            = icon('fas', 'plus')
          .Icons__text
            イベント作成
      .Icons__icon
        = link_to recruit_user_path(current_user) do
          .Icons__icon--plus
            = icon('fas', 'calendar-alt')
          .Icons__text
            イベント管理
      .Icons__post
        = link_to "ログアウト", destroy_user_session_path, method: :delete
    - else
      .Icons__icon
        
      .Icons__icon
        
      .Icons__icon

      .Icons__post
        = link_to "ログイン", new_user_session_path

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Spolabo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/notifications'
      = yield